### ISSUE TITLE
filter attribute

### ISSUE THREAD

**Issue by Zecat** [samccone/paper-typeahead#17]
For now, it's a little strange that a typed regexp is interpreted with the default "filterFn".
Example : type "^a" returns values beginning with "a".

Unless the user provides "filterFn", a "filter" String attribute could handle the most frequently used case, within a predefined set : "begins-with", "ends-with", "contain", "every-words", "any-of-words", "letters", "none-of-words" …
Internally, paper-typeahead will associate each "filter" 's possible value to a regexp.

**Comment by samccone** [comment]
A user can pass a custom filterFn if they would like, and this covers this case and a few more :)
The idea here is to prevent attribute bloat.
