### ISSUE TITLE
Selection didn't work with iron-selector 1.0.8

### ISSUE THREAD

**Issue by Zecat** [samccone/paper-typeahead#20]
For now, update bower components broke the element, results are not selectable anymore.

IronSelectableBehavior -> get items( ) has been change to _updateItems( )

https://github.com/PolymerElements/iron-selector/commit/92b0bbc31ef7dbb9bbbd1beb0db75877e3babcca

**Comment by samccone** [comment]
so are you saying when you updated a bower_component things broke?

Or was this broken out of the box?

**Comment by Zecat** [comment]
I mean, you know that iron-selectable query only the distributed elements, so we use a hack, we override get items() using querySelectorAll('.selectable') for our local '.selectable' elements to be part of items array. In iron-selector 1.0.8, there change the logic using [_updateItems()](https://github.com/PolymerElements/iron-selector/commit/92b0bbc31ef7dbb9bbbd1beb0db75877e3babcca#diff-c64eedc3daead72759c9014ab0eb08c4R220) and items is now [readOnly](https://github.com/PolymerElements/iron-selector/commit/92b0bbc31ef7dbb9bbbd1beb0db75877e3babcca#diff-c64eedc3daead72759c9014ab0eb08c4R114) so the hack is not working anymore. I see 3 solutions :
- update the hack
- use iron-selector instead of IronSelectableBehavior
- (re)create paper-typeahead-results implementing IronSelectableBehavior

The problem for 2. and 3. is that for now, paper-input-container is part of the items array. Tell me if I am not clear enough.
