### ISSUE TITLE
Update package.json to Polymer 1.2.0

### ISSUE THREAD

**Issue by camerongreen** [samccone/paper-typeahead#24]
Polymer.dom(...).observeNodes is not a function in Polymer 1.1.x

This is called in a couple of files pulled down by bower.

bower_components/iron-selector/iron-selectable.html:        Polymer.dom(this).unobserveNodes(this._observer);
bower_components/iron-selector/iron-selectable.html:      return Polymer.dom(node).observeNodes(function(mutations) {
bower_components/paper-input/paper-input-container.html:      this._prefixObserver = Polymer.dom(this.$.prefix).observeNodes(
bower_components/paper-input/paper-input-container.html:        Polymer.dom(this.$.prefix).unobserveNodes(this._prefixObserver);

**Comment by samccone** [comment]
:+1: 

@camerongreen any interest in opening a PR here?
