### ISSUE TITLE
Update bower.json to allow patch and minor updates

### ISSUE THREAD

**Issue by Gabez0r** [samccone/paper-typeahead#25]
Bower.json should have its dependencies' versions marked with a ^ instead of a ~, which would allow both patches and minor updates to be available instead of just patches. Currently, this leads to several conflicts on projects using more recent polymer elements.

**Comment by samccone** [comment]
Polymer does not follow semver when updating elements. For that reason I am using ~. If you have specific dep issues, let me know which ones and we can update the version in bower.json.
