### ISSUE TITLE
Allow object arrays as data source & use newest polymer versions

### ISSUE THREAD

**Issue by Compufreak345** [samccone/paper-typeahead#28]
Hi,

not sure if you are interested in it - but in my fork, in addition to tell bower to always use the newest Polymer versions, I added a "getValFn" to your code, so I can put my own function in there, allowing me to use object arrays as data source. Strings should still work the same way as before. I am using it for an auto-fill-form, giving objects with pre-filled fields and filtering them by their title. I updated the demo to show what it does, using the last 2 inputs, filling each other if one gets filled. 

https://compufreak345.github.io/paper-typeahead/components/paper-typeahead/demo/

So, this is my fork : 
https://github.com/compufreak345/paper-typeahead

Are you interested in a pull request or is it a too specific problem?
I'm not 100% satisfied with strings being returned as value when nothing was selected, making some special handling necessary, but I couldn't think of a better way.
Unfortunately my automatic code formatting changed some indents, let me know if this is a problem.

Oh, and I just grabbed that country-list I found on google. https://gist.github.com/Keeguon/2310008 . No license mentioned there, if you have any better example let me know xD

**Comment by samccone** [comment]
:+1: PRs welcome
