### ISSUE TITLE
various modifications

### ISSUE THREAD

**Issue by Zecat** [samccone/paper-typeahead#7]
Hi, can you take a look at my 'features' branch on my fork. I generated the component page, link is on my master branch.
#### To summarize :
- I was inspired by the google autocomplete system : the input is always focus when we navigate with the up/down arrows in the results list. With IronMenuBehavior, items are focused and input lose focus, so I used iron-selector and write the arrows handlers myself. Items are still selectable with tab key.
- I've merged the 2 files because I don't think paper-typeahead-results will be used standalone.
- I called the filtredItems "predictions" (fancy thing from Place Autocomplete API) I thought it was cool from the user side.
- To increase API, the user can to control the result layer manually (select/display/hide), but as we don't want the user to display the result layer when the result array is empty, I set it private (_hideResults) and add methods tryDisplayPredictions(), hidePredictions(), selectPrediction(selectedIndex).
- I used hidden$="[[_hideResults]]"  instead of dom-if, to use the $.id selector instead of $$('#id'), I'm sure about the performance on this one ?

> #### from polydoc
> 
> Since it is generally much faster to hide and show elements rather than destroy and recreate them, conditional templates are only useful to save initial creation cost when the elements being stamped are relatively heavyweight and the conditional may rarely (or never) be true in given usages. Otherwise, liberal use of conditional templates can actually add significant runtime performance overhead.
#### Possible improvements inspired from google autocomplete system:
- An attribute as "live-input-update" could do the paper-input's value to update each time the 'iron-selected' changes, but still remembering the initial user input.
- hover an item could directly select it (so the keyboard navigation continues at this point) but if something like "live-input-reload" was in place, the paper-input's value should not update.

Sorry for the long speech ;)

**Comment by samccone** [comment]
hey @Zecat I just took a look, this seems great! would you want to open up a PR? :tada: 
awesome work here, i have made a ton of similar modifications locally I just have not synced everything yet
